### ISSUE TITLE
Angular 4 Compatibility

### ISSUE THREAD

**Issue by carloinqbyteio** [nivikamal/ng2-image-compress#1]
will this work in Angular 4?

**Comment by amal-quovantis** [comment]
@carloinqbyteio 
Hey I just tested this plugin on Angular 4+.It's working fine.
It's reducing the size to almost 1/10 of the original size.
But i had few questions regarding plugin:
1)Why the data-image url is so long - Can we shorten it?
2)Are there any options on compression like maximum compression size or compression till a particular size ratio?

**Comment by nivikamal** [comment]
Hi amal-quovantis 

data-image url is Image.src of compressed image.

You can get latest version from NPM and create ResizeOptions object 
like 
 var option: ResizeOptions = new ResizeOptions();
        option.Resize_Max_Height = 700;
        option.Resize_Max_Width = 450;
        option.Resize_Quality=80;
        option.Resize_Type = 'image/jpg';
and use  any one of static methods from ImageCompressService , 

    static filesToCompressedImageSourceEx(fileList: FileList, option: ResizeOptions)
    static filesArrayToCompressedImageSourceEx(fileList: File[], option: ResizeOptions): 
    static IImageListToCompressedImageSourceEx(images: IImage[], resizeOption: ResizeOptions): 

if you pass Resizeoption with null then 
method takes default value of ResizeOption class

export class ResizeOptions {
    public Resize_Max_Height = 800;
    public Resize_Max_Width = 1000;
    public Resize_Quality = 70;
    public Resize_Type = 'image/jpg';
}

**Comment by nivikamal** [comment]
Update doc. and work with Angular4+
