### ISSUE TITLE
Metadata mismatch during npm build

### ISSUE THREAD

**Issue by siddharthaReddy** [nivikamal/ng2-image-compress#10]
I am seeing the following issue when compiling my angular 4 project which is using "ng2-image-compress": "^1.0.17" - 
ERROR at node_modules/ng2-image-compress/ng2-image-compress.d.ts, found version 4, expected 3
ERROR in ./src/main.ts

What version of ng2-image-compress to use which is compatible with Angular 4 ?

**Comment by nivikamal** [comment]
Try with
 "ng2-image-compress": "1.0.17"   instead of  "ng2-image-compress":
"^1.0.17"

**Comment by nivikamal** [comment]
For Angular 4: use 1.0.17 Version
For all other version use 1.0.19 or 7.0.X version

**Comment by siddharthaReddy** [comment]
@nivikamal thanks that resolved it 👍

**Comment by nivikamal** [comment]
Cool.. let me know if you need any help.
