### ISSUE TITLE
Linux Case Sensitivity Issue

### ISSUE THREAD

**Issue by corsmond** [nivikamal/ng2-image-compress#11]
When building on Linux the build fails because you are referencing the files in lower case even though the filenames are in ProperCase

**Comment by nivikamal** [comment]
Can you give me specific code/filename?

**Comment by corsmond** [comment]
in your code you are referencing all with lower case, but the actual filenames have uppercase letter.

resizeoptions => ResizeOptions
imageutilityservice => imageUtilityService
compressimage => CompressImage

**Comment by nivikamal** [comment]
Try with new version 7.0.6 .

**Comment by corsmond** [comment]
Thanks. That works

**Comment by corsmond** [comment]
Version 7.0.6 uses same case as files.
