### ISSUE TITLE
File Size does not decrease

### ISSUE THREAD

**Issue by wkyleg** [nivikamal/ng2-image-compress#3]
I'm using the following code:

`private onNewProfileImageFile(fileInput): void {
        let reader = new FileReader();
        let file = fileInput.target.files[0];
        reader.readAsDataURL(file);
        reader.onload = (data: any) => {
            console.log(`Uncompressed string length: ${data.target.result.length}`);
        }

        // Get compressed image
        ImageCompressService.filesToCompressedImageSource(fileInput.target.files)
            .then(observableImages => {
                observableImages.subscribe(
                    (image) => {
                        //console.log(image);
                        this.saveProfileImage(image.imageDataUrl);
                    },
                    (error) => {
                        this.global.showToastError("Could not update profile image");
                        console.error("Error while converting");
                    },
                    () => {
                        console.log("complete");
                    });
            });
    }

    private saveProfileImage(image: string): void {
        console.log(`Compressed string length: ${image.length}`);
    }`

In the dev console in chrome I end up seeing: "Uncompressed string length: 643698," then "Compressed string length: 643698."

Looks like the image isn't being compressed.

**Comment by nivikamal** [comment]
Pass image.compressedImage.imageDataUrl in his.saveProfileImage()

Like 
 this.saveProfileImage( image.compressedImage.imageDataUrl);

**Comment by wkyleg** [comment]
Thanks!
