### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function at eval (ng2-image-compress.js:406)

### ISSUE THREAD

**Issue by arasan-augment** [nivikamal/ng2-image-compress#9]
![ng2-img-compress-issue](https://user-images.githubusercontent.com/28711962/49157257-61913780-f345-11e8-98f1-39196d6da2f7.png)

I got an issue with the ng2-image-compress npm package. I've updated rjxs to 6.3.3. But still the issue exist. Kindy do the needful ASAP

Thanks in advance

**Comment by nivikamal** [comment]
use version 7.0.4 
Can you make sure that "filesArrayToSourceImages" accept an array. Can you use a sample application from GitHub 
use 
git clone https://github.com/nivikamal/ng2-image-compress.git

**Comment by arasan-augment** [comment]
![ng2-img-cmprs-error](https://user-images.githubusercontent.com/28711962/49212697-a7530c00-f3e8-11e8-93a7-330daa624c3f.png)

I've installed this npm package few months before and it's not newly added by me. It was worked fine for those few months. For the last 2 days it was not working. I don't know why it's happening

**Comment by nivikamal** [comment]
Try to update your package.json file with 1.0.19 or 7.0.4 

if does not work then update package,json file with old version 
"ng2-image-compress":"1.0.17"

**Comment by NavjotKumar** [comment]
![screenshot from 2018-11-30 12-08-44](https://user-images.githubusercontent.com/33478668/49272790-c7da9f00-f498-11e8-97d0-90ac21891266.png)
It's still giving error for version 1.0.19 and 7.0.4

**Comment by NavjotKumar** [comment]
tried versions 1.0.14, 1.0.19 and 7.0.4 still not working

**Comment by arasan-augment** [comment]
> Try to update your package.json file with 1.0.19 or 7.0.4
> 
> if does not work then update package,json file with old version
> "ng2-image-compress":"1.0.17"

![ng2-image-compress-packagejson-file](https://user-images.githubusercontent.com/28711962/49279095-8ce26680-f4ac-11e8-88ae-7274b73acd2f.png)

I've already using the above 1.0.17 version only. the below error throwing while build using *ng build --prod*
![ng2-image-compress-console](https://user-images.githubusercontent.com/28711962/49286100-637f0600-f4bf-11e8-9ce5-2c9bcea4866d.png)

**Comment by nivikamal** [comment]
You need to update package.json and [ package-lock.json if you have]  file with 
"ng2-image-compress":"1.0.17"             [ remove ^ symbol] and delete node_module and do npm install and try.

**Comment by arasan-augment** [comment]
> You need to update package.json and [ package-lock.json if you have] file with
> "ng2-image-compress":"1.0.17" [ remove ^ symbol] and delete node_module and do npm install and try.

Thanks @nivikamal Now it's working. I'd removed the ^ symbol from package.json and did the given steps to resolve this issue. 

1. rm -rf node_modules/
2. rm -rf package-lock.json
3. npm cache clean --force
4. npm install

Thanks  again...
